#!/bin/bash

EXEC=$(find . -type f -name "Isabelle*.run" | sort |  tail -n 1)

if [ $EXEC = "" ]; then
    echo "Isabelle not found in the current directory. Downloading"
    VERSION=$(curl https://isabelle.in.tum.de/dist/ | grep "linux.tar.gz" | cut -d '=' -f 2 | cut -d ">" -f 1)
    wget https://isabelle.in.tum.de/dist/$VERSION
    tar -xf $VERSION
    rm -f $VERSION
    EXEC=$(find . -type f -name "Isabelle*.run" | sort |  tail -n 1)
fi

if [ -f $EXEC ]; then
  $EXEC &
else
   echo "Isabelle not found in '$EXEC'"
fi
